<?php
/**
 * Icon classes present in fontawesome-subset.min.css.
 *
 * Generated by .github/build-icon-subset.py -- do not edit by hand.
 *
 * @package pixova_lite
 */

return array(
	'fa-brands fa-bitbucket',
	'fa-brands fa-codepen',
	'fa-brands fa-dribbble',
	'fa-brands fa-facebook',
	'fa-brands fa-github',
	'fa-brands fa-google-plus',
	'fa-brands fa-instagram',
	'fa-brands fa-linkedin',
	'fa-brands fa-pinterest',
	'fa-brands fa-tumblr',
	'fa-brands fa-twitter',
	'fa-brands fa-youtube',
	'fa-regular fa-envelope',
	'fa-solid fa-angle-left',
	'fa-solid fa-angle-right',
	'fa-solid fa-bars',
	'fa-solid fa-bold',
	'fa-solid fa-calendar-alt',
	'fa-solid fa-calendar-days',
	'fa-solid fa-check',
	'fa-solid fa-close',
	'fa-solid fa-code',
	'fa-solid fa-comment',
	'fa-solid fa-comments',
	'fa-solid fa-envelope',
	'fa-solid fa-eye',
	'fa-solid fa-folder',
	'fa-solid fa-folder-blank',
	'fa-solid fa-heart',
	'fa-solid fa-multiply',
	'fa-solid fa-navicon',
	'fa-solid fa-remove',
	'fa-solid fa-times',
	'fa-solid fa-user',
	'fa-solid fa-user-alt',
	'fa-solid fa-user-large',
	'fa-solid fa-xmark',
);
